### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by ImSemaj** [Ryzzzen/manaflux#33]
Currently just getting stuck on this screen. I'm updated to the latest version.

![image](https://user-images.githubusercontent.com/42705401/44623469-440f8600-a89d-11e8-8c49-30a4421e4f7f.png)

Found this on another thread just thought I'd throw in 
![image](https://user-images.githubusercontent.com/42705401/44623473-74572480-a89d-11e8-82fe-edc7c618b2d4.png)

![image](https://user-images.githubusercontent.com/42705401/44623463-1aeef580-a89d-11e8-9653-994c738b94f2.png)
![image](https://user-images.githubusercontent.com/42705401/44623465-2b06d500-a89d-11e8-91bf-71d65a97048b.png)

If you need more info from me let me know.

**Comment by thomas-cardon** [comment]
Hello! If you messed up the directory, it's the reason why it's not loading. There's navigation arrows alongside the **HOME** button, click on them to find the "**Reset Settings**" button. Click this button if you know where is your directory, or **start League of Legends BEFORE clicking this button**, so Manaflux will try to find it automatically (this function has received upgrades, bugfixes etc, if it doesn't find it, you'll be prompted with a box asking you to find by yourself the directory). **The directory must have LeagueClient.exe inside**. By default it's `C:\Riot Games\League of Legends\`.

(The navigation arrows shows when you click on settings first, because there's multiple setting pages!)

**Comment by thomas-cardon** [comment]
I'll add a feature to prevent user errors while selecting your League of Legends directory.
