### ISSUE TITLE
Please add U.GG

### ISSUE THREAD

**Issue by daicain** [Ryzzzen/manaflux#41]
Please add support for U.GG

**Comment by thomas-cardon** [comment]
https://github.com/Ryzzzen/manaflux/commit/f0943826a2e817945f4307a3d7f70da294655a14. U.GG was supposed to be an upcoming provider for the next version but It might come a bit later since I'm having issues with their website and that's not the priority, (there's a lot of issues first!), but a lot of other things are coming and I'll see what I can do once I've released this version. Hope you understand.

**Comment by daicain** [comment]
> [f094382](https://github.com/Ryzzzen/manaflux/commit/f0943826a2e817945f4307a3d7f70da294655a14). U.GG was supposed to be an upcoming provider for the next version but It might come a bit later since I'm having issues with their website and that's not the priority, (there's a lot of issues first!), but a lot of other things are coming and I'll see what I can do once I've released this version. Hope you understand.

Of course. Thank you for your hard work !
