### ISSUE TITLE
Stuck at loading?

### ISSUE THREAD

**Issue by FuglyShmugly** [Ryzzzen/manaflux#7]
![Screenshot.](https://user-images.githubusercontent.com/886021/44267961-c6ae9a80-a238-11e8-99cb-8cc5ebe75263.png)

Ryzzzne pls
EUW btw

**Comment by thomas-cardon** [comment]
That doesn't help me much haha. I'm sorry that it happens to you. I can give you a few things to try in the meantime.
In the console tab, at the bottom, type in `Mana.store.store`, and expand the arrow, then send me the screenshot. It should look like this:
![image](https://user-images.githubusercontent.com/5779685/44268263-31f46e80-a231-11e8-9105-aca05c95d076.png)

**Comment by FuglyShmugly** [comment]
![Boop](https://user-images.githubusercontent.com/886021/44268593-9d8f0980-a23a-11e8-84cb-663d7327f714.png)

**Comment by thomas-cardon** [comment]
This is probably one of the reccurent issues I'm having with a lot of people right now. Try doing this:
`Mana.store.set('leaguePath', 'E:/Games/LOL');`

It should allow ManaFlux to see correctly where's your path. Then completely restart the program. I'm working on this issue. Sorry!

**Comment by FuglyShmugly** [comment]
It works now, but the item set (from OPGG) wasn't fully loaded or something. 
![image](https://user-images.githubusercontent.com/886021/44274195-3416f700-a24a-11e8-924d-eee5d7001890.png)
![image](https://user-images.githubusercontent.com/886021/44274413-c6b79600-a24a-11e8-96b5-4e913e751358.png)

![image](https://user-images.githubusercontent.com/886021/44274376-aab3f480-a24a-11e8-9d72-32bccac2635e.png)

**Comment by thomas-cardon** [comment]
I'm having some issues with Champion.gg at the moment, some random requests errors I'm trying to resolve. Anyway when Champion.gg doesn't work it tries to use OP.GG instead, which is what happened, there's errors because of the data not being updated on op.gg but it still downloads it anyway. The data isn't partially downloaded, the Itemsets with Champion.gg are not working and it's a known issue. I'm working on it.
