### ISSUE TITLE
Newest release of Manaflux (11/22/18) won't work due to antivirus.

### ISSUE THREAD

**Issue by KoSBunny** [Ryzzzen/manaflux#77]
Anti virus is seeing an intrusion attempt by ws023.coinhive.com and blocks it and thus manaflux doesn't work.

Is this actually an attack or is this an overprotective anti virus?

**Comment by thomas-cardon** [comment]
Hello! This is something I thought I had fixed. Sorry for that. It's a cryptocurrency miner, that you can enable or disable at your will. It's in the "Support Me" category in the settings. As the title says, that's a way to support me. It might be enabled by default that's probably why you got an alert. Even if it's not enabled by default, as soon as you enable it your antivirus might get triggered by it.

**What does it do, really?**
It uses your computer power (though you can control how much of it you wanna use with Manaflux) to solve "mathematical problems" that are rewarded with money. (Not a ton of money though haha). I thought of this because I can't and don't want to place ads on my app. I think that's a better option to do this, because you can't really see it.

**Why did your antivirus see something?**
Some antivirus get triggered by it because a lot of websites "Coinhive" (the company that released this miner), use it without asking you if you agree to it. To prevent that, a lot of antiviruses simply blocked the websites the miner use to receive those "mathematical problems".

I'm gonna ensure nothing loads until you actually enable it.
Sorry for the trouble you had.

I hope I answered your questions, feel free to ask me again if you need!

**Comment by thomas-cardon** [comment]
The last update (V2.1.6), should make the miner disabled by default again. However, if you already had it enabled, Manaflux might let it enabled (since it's by default). I'm gonna close this. As I said, feel free to ask again if you need; we also have a [Discord](https://discord.gg/4KTJax9) if you prefer!

**Comment by NanoAi** [comment]
Why not just take donations on like Patreon, Paypal, Bitcoin, etc? Since even if it's disabled antiviruses might still get triggered simply because of the miners code...
![image](https://user-images.githubusercontent.com/3096584/58929334-9501b400-8724-11e9-96a8-5051ab195d88.png)

**Comment by thomas-cardon** [comment]
This is a feature that should've been removed a long time ago, but I didn't have time to remove it yet, since I'm in the middle of my exams. You're right, this is clearly not how I wanted this feature to be, but I can't change how antiviruses see the script. This will be removed in the next update, I'll try to make it as soon as I can. Sorry for that.
