### ISSUE TITLE
Manaflux is unusable now

### ISSUE THREAD

**Issue by KoSBunny** [Ryzzzen/manaflux#78]
Ever since the update for preseason and the addition of the mining feature to help support you the product has become unusable and couldn't serve its actual purpose of providing rune pages. I just had to remove everything from manaflux. The rune pages stopped loading and updating etc.

It also became a security risk. Even windows thought it was one.

**Comment by xnetcat** [comment]
HI @KoSBunny,

Can you tell me exactly what your problems are? It would be best if you could send a request using the button in the upper right corner of the application or find the appropriate logs and send them here.

You can contact me on the discord KKo7#5194 / https://discordapp.com/invite/4KTJax9

**Comment by xnetcat** [comment]
Also take a look here https://github.com/Ryzzzen/manaflux/issues/76

**Comment by thomas-cardon** [comment]
Exactly, we can't resolve issues that we don't know about. We need logs (they're sent by using the feedback button), steps to reproduce if possible, when it happened, etc. Manaflux doesn't have any security issues either. It's a false positive due to the mining feature. That's why it's not enabled by default.

**Comment by xnetcat** [comment]
Issue closed, since there's no response, and your issue might be fixed. In case it is not, feel free to open it again.
