### ISSUE TITLE
Downloading takes ages

### ISSUE THREAD

**Issue by N4zroth** [Ryzzzen/manaflux#83]
I've updated yesterday and since then, downloading takes ages. 40 seconds aren't enough sometimes even though I'm on a 250 MBit/s connection. What's happening?

**Comment by kko7** [comment]
Hi @N4zroth can you send logs ?

**Comment by kko7** [comment]
And/Or contact me on discord https://discordapp.com/invite/4KTJax9 / KKo7#5194

**Comment by thomas-cardon** [comment]
Hello! There seems to be actually an issue if Manaflux tries to download using the website METAsrc, this website takes a long time to load. It might be the reason why it's taking so long, especially if you play URF, since I've added support for this game mode in the last update, and for now the only website supported is this one.

**Comment by thomas-cardon** [comment]
Closing the issue since there's no response. Feel free to open it again if you need.
